kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-connect-ui
  namespace: stream
spec:
  template:
    metadata:
      labels:
        app: kafka-connect-ui
    spec:
      containers:
      - name: kafka-connect-ui
        image: landoop/kafka-connect-ui
        # command: ["landoop/kafka-connect-ui"]
        ports:
        - containerPort: 8000
        env:
        - name: CONNECT_URL
          value: "http://debezium-connect-source:8083"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-ui
  namespace: stream
  labels:
    app: kafka-connect-ui
spec:
  ports:
  - name: client
    port: 8000
    nodePort: 30800
    protocol: TCP
  selector:
    app: kafka-connect-ui
  type: NodePort
