{
 "title": "Customer Postgres",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Customer Rec Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  count(customername)\nFROM customer\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pie Chart States",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(100),\n  state AS outcome,\n  count(id) AS measurement\nFROM customer_nf\nWHERE state!=''\nGROUP BY state\nORDER BY measurement"
    }
   ]
  },
  {
   "title": "Air Mexico Branches",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT customeraddress from customer where customername='Air Mexico' order by customeraddress"
    }
   ]
  },
  {
   "title": "Table CUSTOMER_NF",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "rawSql": "SELECT * FROM CUSTOMER_NF" }
   ]
  }
 ]
}