version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=talend
            - POSTGRES_PASSWORD=talend
            - POSTGRES_DB=talend
        ports:
            - "5433:5432"
        volumes:
            - ./backups:/home/backups
