version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=airflow
        ports:
            - "5433:5432"
        volumes:
            - /home/osboxes/talend_kub_airflow/postgres/backups:/home/backups
